### ISSUE TITLE
Support for lists in `to_dict`

### ISSUE THREAD

**Issue by salotz** [hoedt/upsilonconf#7]
Currently `from_dict` works to recursively go down through lists to get sub `FrozenConfiguration` objects. By example:

```
>>> conf = FrozenConfiguration.from_dict({"things": [    {"a": 0, "b": 1},     {"a": 2, "b": 3}, ]})
FrozenConfiguration(things=(FrozenConfiguration(a=0, b=1), FrozenConfiguration(a=2, b=3)))

>>> conf.to_dict()
{'things': (FrozenConfiguration(a=0, b=1), FrozenConfiguration(a=2, b=3))}
```

And then I cannot serialize this to e.g. YAML simply.

**Comment by hoedt** [comment]
`FrozenConfiguration.from_dict` converts `dict`s to `FrozenConfiguration` objects because it is the easiest way to get immutable mappings.
If you are just interested in conveniently writing these to YAML, you can just use [`upsilonconf.save_config`](https://hoedt.github.io/upsilonconf/generated/upsilonconf.save_config.html#upsilonconf.save_config) with a filename that ends with `".yaml"` or `".yml"`.

This being said, the main problem is that upsilonconf does not really support sequences of configurations at this point.
The main reason is because I want to reserve them for representing configuration grids (e.g. for hyper-parameter search).
However, if you have a specific need for lists of configs, this is something I am open for and can look into.
If this is the case, I would appreciate it if you could start a new issue and explain your use case for sequences of sub-configs.

PS: To be precise, this is a particular side-effect of `FrozenConfiguration.from_dict`. 
If you would use `PlainConfiguration.from_dict`, you'd find that the `dict`s in your list are not recursively converted (because a `list` of `dict` is not considered part of the configuration currently).

**Comment by salotz** [comment]
I see, kind of. In my use case they would be YAML files written by hand.

> The main reason is because I want to reserve them for representing configuration grids (e.g. for hyper-parameter search).

IMO that is a feature that should be built on a lower level general purpose config system (which I thought was the goal of upsilonconf and one reason I'm not using e.g. hydra on top of OmegaConf). And I can use another hyperparameter matrix tool for that like ml_collections. E.g. a special schema of a config file that that can specify matrices of parameters that can then be used to generate specific full configs.

**Comment by salotz** [comment]
So that said I'm not sure its another issue, except that it competes with the other goals you've mentioned here.

**Comment by hoedt** [comment]
> my use case they would be YAML files written by hand.

Can you be a bit more specific about what you want to achieve by using lists? 
After all, even if the config is written by hand, it would be possible to just add a key for each list item (e.g. `item0`, `item1`, ...).
Do you wish to represent configuration options (similar to what we need for hyper-parameter searches), is it something like `*args` vs `**kwargs` or is it something entirely different?

> E.g. a special schema of a config file that can specify matrices of parameters

It seems that you are interested in using lists to represent different options for configurations.
Is this correct?

> that is a feature that should be built on a lower level general purpose config system

You are probably right. Even in the case of hyper-parameter search, the representation of configuration options should probably happen in this library.

> I'm not sure it's another issue

You are right (again). I completely missed the title and thought this was about saving configuration objects (rather than full support for `list` values).

---

Given my current understanding of your issue, I think the following tweaks should solve the problem:
 - Some sort of `Options` class to represent a `list` containing different value options for a parameter.
 - A `ConfigurationGrid` class that allows to index and iterate the different configurations (with one of the options filled out).
 - A `to_grid` method that allows to convert a configuration object with `Options` values to be represented as a grid.

Is this something you could work with?

**Comment by hoedt** [comment]
Thank you for the additional information. That does make things a little clearer.

Just to make sure I understand you correctly, are the following statements correct?
 - the items in the list **don't** represent configuration options,
 - you **don't** need any special operations on these list values,
 - you **do** need an immutable configuration object.
 - you **do** need round-trip functionality for `from_dict`, `to_dict`.

Also, would you be able to answer the following questions:
 - should the `dict`s inside the `list` be represented as configuration objects?
 - how do you plan to use these items in your code?

This final question probably requires some background information.
Configuration objects are designed to conveniently represent `kwargs` of python functions.
After all, `kwargs` are typically used to "configure" functions in python.
Given your example of the rocks config, I would assume that there is some function of the form `def func(x, y, z, rocks)` and this function can be called using `func(x, y, z, rocks=config.rocks)` or `func(x, y, z, **config)`.
Is the goal to call some `sub_func` with the different configurations in the list or is the body of `func` agnostic of the kind of elements that are passed through the `rocks` kwarg?

Sorry for the interrogative tone, but I just want to make sure that I understand you and your use-case correctly.

PS: I just realised that round-trips on mutable objects inside of an immutable configuration object would require to keep track of the original (mutable) types in the configuration. I am not sure if that kind of overhead is reasonable. What do you think?

**Comment by salotz** [comment]
> Sorry for the interrogative tone, but I just want to make sure that I understand you and your use-case correctly.

No worries! Happy to answer any questions.

> Just to make sure I understand you correctly, are the following statements correct?
>   the items in the list don't represent configuration options,
>   you don't need any special operations on these list values,
>   you do need an immutable configuration object.
>   you do need round-trip functionality for from_dict, to_dict.

Yes to all.

> should the dicts inside the list be represented as configuration objects?

Yes

> how do you plan to use these items in your code?

A simple but illustrative example:

```python
rocks = RockArray([Rock(**rock) for rock in config.rocks])
```

In the large and for converting to structured objects I would use a system like cattrs (linked above), which kind of leads into the background info.

> This final question probably requires some background information.
> Configuration objects are designed to conveniently represent kwargs of python functions.
> After all, kwargs are typically used to "configure" functions in python.

You also have the `*args` you can pass as well. 

> Given your example of the rocks config, I would assume that there is some function of the form def func(x, y, z, rocks) and this function can be called using func(x, y, z, rocks=config.rocks) or func(x, y, z, **config).
> Is the goal to call some sub_func with the different configurations in the list or is the body of func agnostic of the kind of elements that are passed through the rocks kwarg?

I wouldn't do this directly. There would be two possibilities:

1. The one I showed above where you are doing some structuring of the config into classes (in my case attrs "dataclasses"). You can do this manually (as above) or use some kind of system that recursively does the type casting for you (cattrs in my case).
2. Functions that just accept more dynamic "dicts and lists".

For instance:

```python
rocks = config.to_dict()["rocks"]

# would look like this, not list of Configurations
# [{"size" : 10, "weight" : 30}, {"size" : 3, "weight" : 5}]

def dig_rock(size, weight):
    ...

def dig_rocks(rocks)

    for rock in rocks:
        dig_rock(**rock)

dig_rocks(rocks)

```

I think as your design goals states I also think its a bad idea to have the Configuration objects passed into anything other than application entrypoint code. Unless you are at a leaf of the configuration that has no sub-structure, in which case its fine to `func(**config["rocks"][0])`.

I think to summarize is that I think it should kind of be left up to the user of the library to figure out how to do the slicing/structuring of the data in the configuration object. I'm picking up that you were kind of intending to use dict and tuple unpacking as kind of an all-purpose structuring tool, however I don't think that works at scale since it doesn't work recursively itself. That is why I use a tool like cattrs which is specially built to handle this difficult issue.

For instance consider I want to change my weight attributes to unitted values that needs to be specially parsed:

```yaml
rocks:
  - size: 10
    weight: 30 kg
  - size: 3
    weight: 5 kg
```

I would need to change to something like:

```python
rocks = [{"size" : rock["size"], "weight" : parse_quantity(rock["weight"]) for rock in config.to_dict()["rocks"]
```

And this complexity just keeps on scaling linearly with every new config option you add.

My only point is that cleanly handling deeply nested serialized structures like configs is probably something beyond the scope of (in my mind) a simple config merging library. The only general thing you can do is to just recursively convert to lists and dicts and if the user's use case is suitable for tuple/dict unpacking that should flow naturally from that.

---

> PS: I just realised that round-trips on mutable objects inside of an immutable configuration object would require to keep track of the original (mutable) types in the configuration. I am not sure if that kind of overhead is reasonable. What do you think?

Personally I would just rip out anything mutable at all from the library. Its an antipattern and as you are mentioning it makes useful functional things impossible. I plan on never using anything other than FrozenConfiguration.

So I would just consider input "lists" (or tuples) as snapshotted at the point of config creation and forget the original thing existed ever.

**Comment by salotz** [comment]
An additional example with using cattrs for structuring:

```python
from attrs import define

@define
class Rock:
    size: int
    weight: int

@define
class RockArray:
    rocks: list[Rock]

rocks = CONVERTER.structure(RockArray, config.to_dict())
```

Where `CONVERTER` is a potentially customized cattrs converter, which can handle things like parsing special fields like in the units example above.

**Comment by hoedt** [comment]
I think I understand what you want to achieve, but I still don't quite understand how this is related to configuration or why you would need a configuration class.

The use case you illustrate seems to be more about how to convert user input to structured data (which seems to be a problem that is addressed by `cattrs`) than about the configuration of a program.
I still fail to see why it could be a good idea to have a list of configurations as a configuration value unless they are just different sub-configuration options.

Given your example, I would expect something like
```python
with open("config.json") as fp:
    rocks = CONVERTER.structure(RockArray, json.load(fp))
```
to do exactly what you want. 
I do not see the benefit of using an intermediary configuration class in this setting.

> I would just rip out anything mutable at all from the library

Making collections in python immutable comes at a certain cost: all elements in the collection must be immutable as well.
If you would create the frozen configuration from immutable objects, round-trips are no problem, but since you create the frozen configuration from mutable objects, the objects need to be converted and the round-trip becomes impossible (without significant overhead).

**Comment by salotz** [comment]
> I think I understand what you want to achieve, but I still don't quite understand how this is related to configuration or why you would need a configuration class.

I see your point. The main thing I use the configuration class for is the merging operations.

So:

```python
with open("config.json") as fp:
    config = json.load(fp)

final_config = config | defaults

rocks = CONVERTER.structure(RockArray, final_config.to_dict())
```

**Comment by salotz** [comment]
> Making collections in python immutable comes at a certain cost: all elements in the collection must be immutable as well.
If you would create the frozen configuration from immutable objects, round-trips are no problem, but since you create the frozen configuration from mutable objects, the objects need to be converted and the round-trip becomes impossible (without significant overhead).

I'm fine with it being structurally the same. I.e. if you input a tuple from the config and output a list that is fine with me, but I can see why you wouldn't want to make that choice.

**Comment by hoedt** [comment]
Since Python 3.9, you can merge dictionaries in python natively ([PEP-584](https://peps.python.org/pep-0584/)).
If that is not an option for you, I would advise you to use `PlainConfiguration`, because this will not interfere with the incoming types and therefore natively enables round-trips.

I hope this anticlimactic answer works for you.

PS: feel free to fork this project to build an input parser if that is what you need, but I'm afraid that this is not what I had in mind when building upsilonconf.

**Comment by salotz** [comment]
Seems obvious in hindsight, as I hadn't actually used this in practice as of yet...

I would like to have richer operations than just what is in the PEP though, which I was thinking of adding additional feature requests. For instance `merge([config_a, config_b, config_c])` and subtree merge.

Fair enough though thanks for the conversation and sorry for taking so long to get there.
